Disable PersistentKernel
Includes intermediate checking for PrefetchAcrossPersistent
(see Common.py).  Status:

PK=0 : All pass
PK=2 : All pass
PK=2, PAP=1, ExpandPointerSwap=0: most tests pass except these 6:
  FAILED big_tensor/test_big_tensor.py::test_largec
  FAILED big_tensor/test_big_tensor.py::test_biga
  FAILED fractional/test_fractional.py::test_sgemm_fractional_tile_sweep
  FAILED fractional/test_fractional.py::test_dgemm_fractional_tile_sweep
  FAILED fractional/test_fractional.py::test_hgemm_fractional_tile_sweep
  FAILED fractional/test_fractional.py::test_sgemm_fractional_edge

ExpandPointerSwap=1 expands the unroll loop into two sections each of which expects a specific,
hard-coded location for the input and output LDS buffer.  This removes vector ALU instructions which
otherwise are required to swap the LDS read and write pointers.  PAP alternates the buffer
where the prefetch targets and thus requires some logic to jump into the appropriate section
of the unroll loop.  So PAP + EPS needs some extra code for this complexity.  Some of this
is implemented and it works for simple cases, but needs finishing.
Most tests pass except these 11:
  FAILED big_tensor/test_big_tensor.py::test_biga
  FAILED big_tensor/test_big_tensor.py::test_largec
  FAILED flat/test_flat.py::test_sgemm_asm_flat_nt
  FAILED flat/test_flat.py::test_dgemm_asm_flat
  FAILED classic_source/test_classic_source.py::test_dgemm
  FAILED nonbatched/test_nonbatched.py::test_sgemm_asm_nt
  FAILED pre_checkin/test_pre_checkin.py::test_sgemm_asm_nt
  FAILED pre_checkin/test_pre_checkin.py::test_dgemm_asm
  FAILED vector_width/test_vector_width.py::test_hgemm_nn_asm
  FAILED vector_width/test_vector_width.py::test_sgemm_nn_asm
  FAILED fractional/test_fractional.py::test_sgemm_fractional_edge


[ROCm/Tensile commit: da6aa0b68869e51f268e7e8da75c8c47e5f535e6]